# Generated by Django 5.1.1 on 2024-10-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20241008_1601'),
    ]

    operations = [
    ]
