# Generated by Django 5.1.1 on 2024-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('link_imagen', models.URLField(default='http://example.com/default-image.jpg')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='link_imagen',
            field=models.URLField(default='http://example.com/default-image.jpg'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
