# Generated by Django 5.1.1 on 2024-12-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "carrito",
            "0002_carrito_producto_link_imagen_producto_precio_por_kg_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CarritoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name="carrito",
        ),
        migrations.AddField(
            model_name="producto",
            name="supermercado",
            field=models.CharField(default="EROSKI", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="link_imagen",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_por_kg",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name="carritoitem",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="carrito.producto"
            ),
        ),
    ]
